### ISSUE TITLE
Is there a way to monitor sub-tasks on cloud data flow?

### ISSUE THREAD

**Issue by vangalamaheshh** [googlegenomics/dockerflow#17]
For example, let's say, task named "sort bam" executes in parallel (split) by number of input bam files. Right now, on cloud dataflow we can see "sort bam" progress in real time. However, it is impossible to tell the progress of parallel jobs with in "sort bam" task.

Is there a way to monitor such parallel jobs on cloud data flow?

I appreciate your thoughts on this.

Thanks,
Mahesh

**Comment by jbingham** [comment]
Unfortunately, there's not currently. Dataflow is built for massively parallel tasks, and when you're doing it with finer grained parallelism -- like splitting on billions of rows in files a database -- Dataflow is smart enough to dynamically adjust the sharding, so it's not a fixed number of workers. That also makes it harder to monitor exactly how much of the work has completed.

Though you can't do it from the UI, there are a couple of ways you can check status:
- gsutil ls gs://YOUR-WORKSPACE/TASK-NAME and confirm that the log files exist
  (they're written when the tasks complete)
- gcloud alpha genomics operations describe OPERATION-ID
  (you'll have to filter through the results, like maybe "grep TASK-NAME | wc")

Cheers,
Jonathan

**Comment by vangalamaheshh** [comment]
Thanks for the clarification, @jbingham.
The work arounds seem interesting.

Thanks,
Mahesh
