### ISSUE TITLE
using custom docker image from dockerhub

### ISSUE THREAD

**Issue by vangalamaheshh** [googlegenomics/dockerflow#18]
Hi @jbingham -

`
String GATK_IMAGE = "broadinstitute/genomes-in-the-cloud:2.2.3-1469027018";
`

I presume 

`
task.named().docker(GATK_IMAGE)
`

pulls by default form google container registry.

If I want to use my own custom docker image from dockerhub, all I have to do is,

`
String MY_ALIGNMENT_IMAGE = "docker.io/username/image:tag"
`

should do the job?

Let me know.

Thanks,
Mahesh

**Comment by jbingham** [comment]
Yes, that should do it.

Dockerflow actually defaults to Docker hub, not Google Container Registry.

**Comment by vangalamaheshh** [comment]
@jbingham -

Awesome.
Great to know that.

Thanks,
Mahesh
