### ISSUE TITLE
Possible to upload entire directory as output?

### ISSUE THREAD

**Issue by pbilling** [googlegenomics/dockerflow#19]
Hello,

I'm wondering if there is a way to specify an entire directory for upload back to Cloud Storage. I'm running a process that generates a directory tree with many outputs and it's not feasible to specify each one.

I was thinking something similar to the pipelines API, like:

    outputParameters:
    - name: outputPath
      localCopy:
        disk: datadisk
        path: 'output/*'

Thanks!
Paul

**Comment by jbingham** [comment]
Dockerflow supports exactly the same syntax as the Pipelines API. You can
use wildcards, but there's no recursive copy. Perhaps you can do one
outputFile entry per level in your directory tree?

Cheers,
Jonathan

**Comment by pbilling** [comment]
Jonathan,

Thanks for confirming this functionality; turns out I was just using a bad directory path. And thanks for the suggestion for handling a directory tree. I don't think it will work for me this time, because of the size of the tree, but good to know going forward.

Best,
Paul
