### ISSUE TITLE
"UNAUTHENTICATED" error during checking operation

### ISSUE THREAD

**Issue by tantrev** [googlegenomics/dockerflow#21]
After logging into the "owner" account of my Google project using `gcloud init`, dockerflow has been giving me error messages while trying to check the status of pipeline operations with the DirectPipelineRunner:

http://pastebin.com/raw/aY9L09MQ

Dockerflow, however, did not have any authentication issues during job submission.

**Comment by jbingham** [comment]
Progress! You're able to authenticate and submit jobs.

By any chance did you run Dockerflow locally and close your laptop or shell
or change your internet connection while the job was running? Those things
can cause jobs to fail and then status can't be checked. If so, the
solution is to run in the cloud with DataflowPipelineRunner, or keep the
window running the whole time.

Your individual VMs should still complete successfully. If they produce
output files, you should be able to rerun with --resume to pick up where
you left off.

**Comment by tantrev** [comment]
Absolutely!  I've just been running dockerflow from a dedicated "micro" instance on GCE, but you're absolutely right - I think the easiest fix is to just switch over to the dataflow runner.  Just thought I'd point the behavior in case anyone else runs into the same thing with the DirectPipelineRunner. :P

And thank you, I'll definitely give the --resume option a try.

**Comment by jbingham** [comment]
Interesting. A micro instance should have been fine.

It's always possible that there was some temporary network flakiness, and
Dockerflow isn't robust enough to it. Maybe it will work on a second try
even without changes. There's probably a bug lurking there :)
