### ISSUE TITLE
String substitution fails for chained tasks with depth more than two.

### ISSUE THREAD

**Issue by vangalamaheshh** [googlegenomics/dockerflow#31]
If one has a workflow

`Task task1 = TaskBuilder.named("task1").input("sample_name").scatterBy("sample_name");
         task2 = TaskBuilder.named("task2").input("sample_name", "${task1.sample_name}");
         task3 = TaskBuilder.named("task3").input("sample_name", "${task2.sample_name}");`

Currently, the code only handles substituting string replacements only for 2 levels. That means, in task3, we end up having "${task1.sample_name}" for "task3.sample_name" instead of having original value of "sample_name".

The current workaround for this would be,

`WorkflowArgs wf = ArgsBuilder.of().input("task1.sample_name", "${sample_names}")
                                                          .input("task2.sample_name", "${sample_names}")
                                                          .input("task3.sample_name", "${sample_names}").build();`

Clean solution might be to handle string substitutions in a recursive fashion.

- Mahesh

**Comment by jbingham** [comment]
Yup, this is a known issue, and this is the recommended workaround. 

If others find this a blocking problem, or the workaround isn't sufficient, please explain your use case here.

And of course, happy to receive a PR if someone wants to fix it :-)
