### ISSUE TITLE
Running tasks on container engine vs. compute engine

### ISSUE THREAD

**Issue by sharmaashish** [googlegenomics/dockerflow#36]
When DockerFlow launches the individual tasks of a workflow, are these tasks running on separate compute engine VMs, or can they be scheduled to run on a container engine cluster?

**Comment by jbingham** [comment]
They run on separate VMs, sized to fit the tasks. Any benefits you see to using container engine?

**Comment by sharmaashish** [comment]
I'm wondering if it would be more cost effective to pack multiple instances of a container (task) on to a single host machine. 

- Let's say I have to process 100 units of data through a 10-step workflow, where each step takes a min.
- In the current setup, I would therefore need 1000 VMs and it would take me 10mins to complete the job (Let's make the incorrect assumption that time to provision a VM is 0s ). So I would pay for 10,000 mins (due to the 10min GCP minimum).
- However, if I was running this on a container cluster, I would still complete my job in 10mins, but it would only cost me 1,000 minutes of computing.
- And since the time to provision a VM is >> 0, I'd like to reuse hosts as much as possible.

**Comment by sharmaashish** [comment]
Excellent tool btw. We are kicking its tires, to test it on medical imaging pipelines. Would love to see it as a formal member of the GCP ecosystem.

**Comment by jbingham** [comment]
Glad you like it! The docs could be better, I know. 

Yes, there are opportunities for performance optimization. Dockerflow relies on the Pipelines API for the task execution, and it's possible that the Pipelines API could do smarter things to save money, like VM reuse -- if a VM is running, and there's a task that needs the same VM shape, launch the task on the same VM rather than shutting down and starting a new VM.

Have you also looked at [dsub](https://github.com/googlegenomics/dsub
)? It's a task runner like qsub, but for the cloud. If you're doing simple batch jobs rather than more complex graphs, it might be all you need.

**Comment by sharmaashish** [comment]
I thought dsub could only do single node/container workflows. Didn't think there was any possibility of adding, say a CWL workflow, without significant reengineering.
Medical Imaging workflows aren't that different from those in genomics. You have your usual pre-processing followed by feature extraction using say CNNs and/or traditional methods of segmentation+feature extraction, followed by some sort of feature selection (PCA/Random Forest...), before pumping the features through a classifier. Maybe not as deep as genomic workflows, but could consist of 6-10 steps, with some scatter and gather operations.

**Comment by jbingham** [comment]
The way you can do more complex workflows with dsub is to create a bash script that calls dsub multiple times. Then run the bash script with dsub. I don't know if we have a good example of that, but it's definitely been done.

dsub also has a new flag, --after JOB_ID, that lets you do basic task dependency.

For scatter/gather, you could use the --tasks TASK_FILE.tsv option. 

Once you start doing all of these things, you may find that Dockerflow is easier though :)
