### ISSUE TITLE
Push up files in output directory even if job fails halfway through

### ISSUE THREAD

**Issue by kplaney** [googlegenomics/dockerflow#37]
Right now dsub seems like an either-or situation: if you are running a few tasks in your dsub script,  all of which produce intermediate files you write to your OUTPUT_DIR, if task 3 fails, then the output files from tasks 1 and 2 are not pushed up, even if they are written OUTPUT_DIR.  This includes log files written by the user to OUTPUT_DIR to further help in debugging code that worked locally but runs into some snags in the final dsub production pipeline.

It would be very helpful if there was at least an option to push up those intermediate files written to OUTPUT_DIR before the script failed to help with debugging (or amend the script to continue where the script stopped). Even better, perhaps allow the dsub instance to not die upon a script failure (obviously not the default setting) so that the user can log in and diagnose the problem in the production environment.

**Comment by kplaney** [comment]
totally my bad - I did not realize I was on the wrong repo. Will repost!

**Comment by jbingham** [comment]
Thanks!
