### ISSUE TITLE
Multiregional compute instances reading regional gs:// 

### ISSUE THREAD

**Issue by vangalamaheshh** [googlegenomics/dockerflow#40]
Hello -
Currently, dockerflow by default, launches instances across us-* zones. If I have gs:// bucket that is regional, let's say, us-east1-b and a compute instance running on west coast is accessing this bucket. Would I incur egress charges in such case? 

Thank you,
Mahesh

**Comment by jbingham** [comment]
It follows standard GCS pricing, so VMs out of the region incur egress charges. I suggest changing to us-east*.

**Comment by vangalamaheshh** [comment]
Good to know! Thanks, @jbingham 👍
