### ISSUE TITLE
How to get to genomics pipeline/operation ID from Dataflow Job ID?

### ISSUE THREAD

**Issue by vangalamaheshh** [googlegenomics/dockerflow#41]
@jbingham -

dockerflow returns dataflow job id that tells the status of the job. However, it's not useful as to knowing what state of the actual pipeline we are really at. Is there a way to get to genomics pipeline info using dataflow job id?

Thank you,
Mahesh

**Comment by jbingham** [comment]
You can do this from the Dataflow UI, of course. That was the original motivation for creating Dockerflow.

From the command-line or API, which I assume is what you're asking, the VM metadata is your best bet. You can list the VM instances in all of the zones where you have quota. The VM names should begin with a common prefix (I think it's "ggp". For each VM, you can list the metadata with

gcloud compute instances describe ggp-12345

If there's nothing useful there, please paste in the VM name and complete results of describing the VM. It ought to be straightforward to put something more identifiable into the request to Pipelines API.

**Comment by vangalamaheshh** [comment]
@jbingham 

--run-id=STRING
  An id provided by you to label operations to monitor or cancel.

Does this mean, if I use --run-id="unique_identifier" in running dockerflow, would I be able to pull all the operations launched by dockerflow using,

gcloud alpha genomics operations list | grep "name:.*<unique_identifier>"

?
Let me know.

Thanks,
Mahesh

**Comment by jbingham** [comment]
Short answer, I don't know :)

Can you get the status of one of the tasks? You can go to the cloud console:

https://console.cloud.google.com/genomics/operations

Choose your cloud project. You'll see the operation ids of your tasks, both completed and running.

On the command line, run:

gcloud alpha genomics operations describe YOUR-OPERATION-ID

If the client-id is in fact set, you'll see it somewhere in the json that's printed out.
