### ISSUE TITLE
Aborting on pipeline job failure

### ISSUE THREAD

**Issue by vardaofthevalier** [googlegenomics/dockerflow#9]
This issue could potentially be split into two separate ones.  I have run a number of workflows which appear to succeed when viewing the graph in the Dataflow UI, but on closer inspection of the logs for the individual GGP jobs it turns out that some of the individual steps are not actually succeeding.  

Here is the beginning part of a representative "task.log" file produced by one of the failed jobs:

```
2016/09/29 21:49:13 I: Switching to status: pulling-image
2016/09/29 21:49:13 I: Pulling image "b.gcr.io/isb-cgc-public-docker-images/gdc-client:1.0.1"
2016/09/29 21:49:23 I: Pulled image "b.gcr.io/isb-cgc-public-docker-images/gdc-client:1.0.1" successfully.
2016/09/29 21:49:23 I: Switching to status: localizing-files
2016/09/29 21:49:23 I: Docker file /gdc-data/418122394-gdc-user-token.2016-09-29T14_45_50-07_00.txt maps to host location /mnt/gdc-data/418122394-gdc-user-token.2016-09-29T14_45_50-07_00.txt.
2016/09/29 21:49:23 I: Copying <REDACTED> to /mnt/gdc-data/418122394-gdc-user-token.2016-09-29T14_45_50-07_00.txt
2016/09/29 21:49:23 I: Running command: sudo gsutil -q -m cp <REDACTED> /mnt/gdc-data/418122394-gdc-user-token.2016-09-29T14_45_50-07_00.txt
2016/09/29 21:49:40 I: Done copying files.
2016/09/29 21:49:40 I: Switching to status: running-docker
2016/09/29 21:49:40 I: Setting these data volumes on the docker container: [-v /tmp/ggp-160996381:/tmp/ggp-160996381 -v /mnt/gdc-data:/gdc-data]
2016/09/29 21:49:40 I: Running command: docker run -v /tmp/ggp-160996381:/tmp/ggp-160996381 -v /mnt/gdc-data:/gdc-data -e UUID=0001801b-54b0-4551-8d7a-d66fb59429bf -e DISK_SIZE=100 -e GDC_TOKEN=/gdc-data/418122394-gdc-user-token.2016-09-29T14_45_50-07_00.txt -e DOWNLOADED=/gdc-data/1430729090-outputs b.gcr.io/isb-cgc-public-docker-images/gdc-client:1.0.1 /tmp/ggp-160996381
2016/09/29 21:54:13 I: Copying /var/log/google-genomics/*.log to gs://germline-testing/dockerflow/logs/gdcDl/
2016/09/29 21:54:13 I: Running command: sudo gsutil -h Content-type:text/plain -q -m cp /var/log/google-genomics/*.log gs://germline-testing/dockerflow/logs/gdcDl/
2016/09/29 21:59:13 I: Copying /var/log/google-genomics/*.log to gs://germline-testing/dockerflow/logs/gdcDl/
2016/09/29 21:59:13 I: Running command: sudo gsutil -h Content-type:text/plain -q -m cp /var/log/google-genomics/*.log gs://germline-testing/dockerflow/logs/gdcDl/
2016/09/29 22:04:13 I: Copying /var/log/google-genomics/*.log to gs://germline-testing/dockerflow/logs/gdcDl/
2016/09/29 22:04:13 I: Running command: sudo gsutil -h Content-type:text/plain -q -m cp /var/log/google-genomics/*.log gs://germline-testing/dockerflow/logs/gdcDl/
2016/09/29 22:04:44 I: Switching to status: delocalizing-files
2016/09/29 22:04:45 I: Docker file /gdc-data/1430729090-outputs maps to host location /mnt/gdc-data/1430729090-outputs.
2016/09/29 22:04:45 I: Copying /mnt/gdc-data/1430729090-outputs to gs://germline-testing/outputs
2016/09/29 22:04:45 I: Running command: sudo gsutil -q -m cp -L /var/log/google-genomics/out.log /mnt/gdc-data/1430729090-outputs gs://germline-testing/outputs
2016/09/29 22:04:45 E: command failed: CommandException: No URLs matched: /mnt/gdc-data/1430729090-outputs
CommandException: 1 file/object could not be transferred.
 (exit status 1)
```

One thing that I notice in this log file is that it looks like the outputs are expected to be available in a directory with a name following the scheme `<numerical_string>-outputs` that is supposedly located in at the root of the attached disk once the user specified command completes, but this is not how I've specified the outputs myself so I'm not sure where that's coming from.  I've been putting all of my inputs at the root of the attached disk and specifying individual outputs to be collected from there as well.  

As for aborting the Dataflow workflow on failure, I found this comment in the [WaitForOperation](https://github.com/googlegenomics/dockerflow/blob/master/src/main/java/com/google/cloud/genomics/dockerflow/transform/WaitForOperation.java) class:

`// Check for errors and abort if that's the policy`

which suggests that there might be a command line flag that could be used to enable this functionality.  Is this the case, or is there some other mechanism used to set the policy on aborting on failure?

**Comment by jbingham** [comment]
First, on the pipeline not failing:
--abort=true should cause errors to exit. I thought that was the default.
You can explicitly set it if that's not the case -- and you should see it
in stdout if you use DirectPipelineRunner.

For file copies, the goal is that you never need to set local paths
explicitly. Set the GCS path, and then refer to the path on the VM as
${OUTPUT_FILE} or ${INPUT_FILE}, e.g.

In practice, the way it works is that the GCS path is hashed (the random
number you see. That flattens the folder hierarchy, avoids overwrites, and
makes sure files in the same folder remain in the same sort order.

Note that Dockerflow does not support recursive copy or folder copies. You
have to list files individually or use a wildcard, just as with Pipelines
API directly.

Can you share the full command-line and logs? (By private email is fine.)

**Comment by jbingham** [comment]
I found a bug in Dockerflow that was causing the pipeline to NOT abort. I've got a fix that I'll push soon.

That still won't solve whatever's causing the output file to not exist in the first place though. 

First thing to check is that your Docker cmd is only referencing output files using the syntax ${OUTPUT_FILE}, where OUTPUT_FILE is the name of the outputParameter in the yaml, or the outputFile name in the Java. That's the easiest way.

If your Docker cmd script automatically generates output files using some built-in logic of its own, like adding a file suffix, or creating a file or folder in a standard place, so that you can't tell it to write the output to ${OUTPUT_FILE}, you'll need to be explicit about localPath settings. 

Hope that helps!

**Comment by vardaofthevalier** [comment]
I actually do need to be explicit about the path settings in this particular case, but it appears that the localPath settings that I've specified for the particular outputParameter are being overwritten somewhere.  I will share the workflow file, command line and logs via email shortly.

**Comment by jbingham** [comment]
In that case, sounds like I've got another bug! I'll take a look at your example and add a test case.
